-- 부서, 회원, 지역 테이블에서 아래와 같이 사원번호, 이름(별칭), 직무 아이디, 부서 아이디, 부서명, 지역(별칭)을 동등 조인을 활용하여 조회하십시오.
SELECT E.EMPLOYEE_ID,
       CONCAT(CONCAT(E.FIRST_NAME, ' '), E.LAST_NAME) NAME,
       -- CONCAT의 경우 인자를 2개밖에 사용하지 못하므로 CONCAT을 여러번 사용하여 작업해줘야함) => ||로 대체 가능
       E.JOB_ID,
       D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME,
       L.CITY || ' ' || L.STATE_PROVINCE CITY
    FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
    WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
    ORDER BY D.DEPARTMENT_ID;
    
SELECT E.EMPLOYEE_ID,
       CONCAT(CONCAT(E.FIRST_NAME, ' '), E.LAST_NAME) NAME,
       E.JOB_ID, D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME,
       L.CITY || ' ' || L.STATE_PROVINCE CITY
    FROM DEPARTMENTS D INNER JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
    ORDER BY D.DEPARTMENT_ID;
    
SELECT E.EMPLOYEE_ID,
       CONCAT(CONCAT(E.FIRST_NAME, ' '), E.LAST_NAME) NAME,
       E.JOB_ID,
       E.DEPARTMENT_ID,
       D.DEPARTMENT_NAME,
       L.CITY || ' ' || L.STATE_PROVINCE CITY
    FROM DEPARTMENTS D JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
    ORDER BY D.DEPARTMENT_ID;
    
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME || ' ' || E.LAST_NAME NAME,
       E.JOB_ID,
       DEPARTMENT_ID,
       D.DEPARTMENT_NAME,
       L.CITY || ' ' || L.STATE_PROVINCE CITY
    FROM DEPARTMENTS D JOIN EMPLOYEES E
    USING(DEPARTMENT_ID)
    JOIN LOCATIONS L
    USING(LOCATION_ID)
    ORDER BY DEPARTMENT_ID;
    
-- 주의) NATURAL JOIN은 문법은 맞지만 결과값이 다르게 나옴
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME || ' ' || E.LAST_NAME NAME,
       E.JOB_ID,
       DEPARTMENT_ID,
       D.DEPARTMENT_NAME,
       L.CITY || ' ' || L.STATE_PROVINCE CITY
    FROM DEPARTMENTS D NATURAL JOIN EMPLOYEES E
    NATURAL JOIN LOCATIONS L
    ORDER BY DEPARTMENT_ID;
    
    
-- 위의 검색 조건에 직무 아이디가 IT_PROG인 조건을 추가하여 동등 조인으로 검색하십시오.
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME || ' ' || E.LAST_NAME NAME,
       E.JOB_ID,
       D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME,
       L.CITY || ' ' || L.STATE_PROVINCE CITY
    FROM DEPARTMENTS D, EMPLOYEES E, LOCATIONS L
    WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID
    AND D.LOCATION_ID = L.LOCATION_ID
    AND E.JOB_ID = 'IT_PROG'
    ORDER BY D.DEPARTMENT_ID;
    
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME || ' ' || E.LAST_NAME NAME,
       E.JOB_ID,
       D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME,
       L.CITY || ' ' || L.STATE_PROVINCE CITY
    FROM DEPARTMENTS D INNER JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    AND E.JOB_ID = 'IT_PROG'
    INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
    AND E.JOB_ID = 'IT_PROG'
    ORDER BY D.DEPARTMENT_ID;
    
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME || ' ' || E.LAST_NAME NAME,
       E.JOB_ID,
       D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME,
       L.CITY || ' ' || L.STATE_PROVINCE CITY
    FROM DEPARTMENTS D INNER JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
    WHERE E.JOB_ID = 'IT_PROG'
    ORDER BY D.DEPARTMENT_ID;
    
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME || ' ' || E.LAST_NAME NAME,
       E.JOB_ID,
       D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME,
       L.CITY || ' ' || L.STATE_PROVINCE CITY
    FROM DEPARTMENTS D JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
    WHERE E.JOB_ID = 'IT_PROG'
    ORDER BY D.DEPARTMENT_ID;    
    
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME || ' ' || E.LAST_NAME NAME,
       E.JOB_ID,
       DEPARTMENT_ID,
       D.DEPARTMENT_NAME,
       L.CITY || ' ' || L.STATE_PROVINCE CITY
    FROM DEPARTMENTS D JOIN EMPLOYEES E
    USING(DEPARTMENT_ID)
    JOIN LOCATIONS L
    USING(LOCATION_ID)
    WHERE E.JOB_ID = 'IT_PROG'
    ORDER BY DEPARTMENT_ID;

SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME || ' ' || E.LAST_NAME NAME,
       E.JOB_ID,
       DEPARTMENT_ID,
       D.DEPARTMENT_NAME,
       L.CITY || ' ' || L.STATE_PROVINCE CITY
    FROM DEPARTMENTS D NATURAL JOIN EMPLOYEES E NATURAL JOIN LOCATIONS L
    WHERE E.JOB_ID = 'IT_PROG'
    ORDER BY DEPARTMENT_ID;
      