-- 업무가 SALESMAN인 사원만 사원번호,이름,급여,부서명,근무지를 출력하십시오
SELECT  E.EMPNO, E.ENAME, E.SAL, D.DNAME, D.LOC
    FROM DEPT D, EMP E
    WHERE E.DEPTNO = D.DEPTNO AND E.JOB = 'SALESMAN';
    
SELECT E.EMPNO, E.ENAME, E.SAL, D.DNAME, D.LOC
    FROM DEPT D JOIN EMP E
    USING(DEPTNO)
    WHERE E.JOB = 'SALESMAN';
    
SELECT E.EMPNO, E.ENAME, E.SAL, D.DNAME, D.LOC
    FROM DEPT D NATURAL JOIN EMP E
    WHERE E.JOB = 'SALESMAN';
    
SELECT E.EMPNO, E.ENAME, E.SAL, D.DNAME, D.LOC
    FROM DEPT D INNER JOIN EMP E
    ON D.DEPTNO = E.DEPTNO
    WHERE E.JOB = 'SALESMAN';

SELECT E.EMPNO, E.ENAME, E.SAL, D.DNAME, D.LOC
    FROM DEPT D JOIN EMP E
    ON D.DEPTNO = E.DEPTNO
    WHERE E.JOB = 'SALESMAN';